### ISSUE TITLE
multitenancy ./build-all failing

### ISSUE THREAD

**Issue by TheLoneRangerShack** [NFLabs/z-manager#10]
I'm trying to setup multitenancy to play with, so I checked out the code from https://github.com/NFLabs/z-manager and ran build-all.sh under multitenancy, but it's failing with this error:

go build ./...
# github.com/getlantern/golog

../third_party/go/src/github.com/getlantern/golog/golog.go:98: undefined: atomic.Value
Unable to 'go build' the server

I'm not familiar with Go; what's going wrong here?

**Comment by khalidhuseynov** [comment]
Thanks for the interest in Z-Manager.
May I know the version of Go you're using? First of all, update your Go to
version 1.4 or higher.

**Comment by TheLoneRangerShack** [comment]
Thanks for the response.
I'm using Go 1.5.1 (the output of `go version` is `go version go1.5.1 linux/amd64`) and I'm on Centos 6.4

**Comment by bzz** [comment]
Just to nail the case of different go version existing on your system, could you please add
`go version` to [build-all.sh#L60](https://github.com/NFLabs/z-manager/blob/master/multitenancy/build-all.sh#L60) and post back the results of running it again?

**Comment by TheLoneRangerShack** [comment]
Thanks for the response. It's strange but I'm no longer able to reproduce this issue. The build is working fine now. Thanks for your help!
