### ISSUE TITLE
Zeppelin process died

### ISSUE THREAD

**Issue by Emaasit** [NFLabs/z-manager#3]
Iam wondering why my Zeppelin process died. Here is the log file:

Select the type of Zeppelin installation:
1. Default (Hadoop 2.4.0; Spark 1.3.1; local mode)
   Good for quickstart:
       does not require local Spark installation
       does not require external Spark cluster
2. Advanced (pick versions and adjust configuration to your cluster)
1

Configuration is finished now,
please review the options you have chosen before installation begins:

Spark version: 1.3.1
Hadoop version: 2.4.0
Spark master URL: None
Resource manager: Spark standalone
Zeppelin port: 8080

y(es)/n(o) ?
y

Initiating installation...

[2015-06-27T22:31:52+0000]: Downloading Apache Zeppelin (incubating) from zeppelin-0.5.0-incubating-SNAPSHOT-spark1.3.1-hadoop2.4.0.tar.gz...
###### ################################################################## 100.0%

[2015-06-27T22:32:28+0000](Done): Unpack zeppelin-0.5.0-incubating-SNAPSHOT-spark1.3.1-hadoop2.4.0.tar.gz to zeppelin-0.5.0-incubating-SNAPSHOT ...

[2015-06-27T22:32:32+0000](Done): Downloading Zeppelin configuration file ...
###### ################################################################## 100.0%

[2015-06-27T22:32:32+0000](Done): Pyspark found at /python:/python/lib/py4j-0.8.2.1-src.zip
[2015-06-27T22:32:32+0000](Done):   Reading the zeppelin-env.sh

To run Apache Zeppelin (incubating) now do:
 ./bin/zeppelin-daemon.sh start
 and visit http://localhost:8080
ubuntu@ip-172-31-25-168:~$ ls
zeppelin-0.5.0-incubating-SNAPSHOT
zeppelin-0.5.0-incubating-SNAPSHOT-spark1.3.1-hadoop2.4.0.tar.gz
ubuntu@ip-172-31-25-168:~$ cd zeppelin-0.5.0-incubating-SNAPSHOT
ubuntu@ip-172-31-25-168:~/zeppelin-0.5.0-incubating-SNAPSHOT$ ./bin/zeppelin-daemon.sh start
Log dir doesn't exist, create /home/ubuntu/zeppelin-0.5.0-incubating-SNAPSHOT/logs
Pid dir doesn't exist, create /home/ubuntu/zeppelin-0.5.0-incubating-SNAPSHOT/run
Zeppelin start                                             [  OK  ]
Zeppelin process died                                      [FAILED]
ubuntu@ip-172-31-25-168:~/zeppelin-0.5.0-incubating-SNAPSHOT$

**Comment by bzz** [comment]
@Emaasit thank you for your interest in Apache Zeppelin (incubating) and Z-Manager!

It looks like your installation went fine, so as soon as Zeppelin is incubating under Apache - the way to get help with it would be to ask [the community](http://zeppelin.incubator.apache.org/community.html) on the user@ mailing list.

One way to get help quicker is to attach logs from your Zeppelin instance to the email on the list, you can find all logs under `~/zeppelin-0.5.0-incubating-SNAPSHOT/logs/`

Hope this helps!
